#!/bin/sh
BROWSERIFY="node_modules/.bin/browserify --detect-globals false"
BUNDLE_EXAMPLE="$BROWSERIFY -t reactify -t envify -x react -x react-menu"
NODE_ENV=development $BROWSERIFY -t reactify -t envify -r react -r ./lib:react-menu > examples/global-bundle.js

NODE_ENV=development $BUNDLE_EXAMPLE examples/basic/app.js > examples/basic/app-bundle.js
