#!/bin/sh -e

JSX=node_modules/jsx-loader/node_modules/react-tools/bin/jsx

rm -rf build
mkdir -p build

node -p 'p=require("./package");p.name="react-menu";p.main="build/lib/index.js";p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)' > build/package.json

for FILE in $(find lib -name '*.js'); do
  DIRNAME=$(dirname ${FILE})
  mkdir -p build/${DIRNAME}
  DESTNAME=build/${FILE}

  ${JSX} --harmony ${FILE} > ${DESTNAME}
done

echo "Now run \`npm deploy build\` to push the latest to npm"
